In [1]:
import numpy as np

In [2]:
# Qn1:. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

# code->
arr = np.random.randint(1,100,(3,3))

In [3]:
arr

array([[45, 76, 24],
       [96, 17, 68],
       [87,  4, 42]])

In [4]:
arr.T

array([[45, 96, 87],
       [76, 17,  4],
       [24, 68, 42]])

In [5]:
# Qn2: Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

# code->
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
# Qn3: Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

# code->
arr = np.random.rand(4, 4)
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Original 4x4 Array:\n", arr)
print("6x6 Array with Border:\n", bordered_arr)

Original 4x4 Array:
 [[0.43137811 0.71643378 0.44948862 0.89443169]
 [0.77216013 0.72452743 0.16553568 0.95476193]
 [0.68600633 0.14905595 0.94138629 0.60097784]
 [0.64063124 0.97396331 0.93891772 0.24079405]]
6x6 Array with Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.43137811 0.71643378 0.44948862 0.89443169 0.        ]
 [0.         0.77216013 0.72452743 0.16553568 0.95476193 0.        ]
 [0.         0.68600633 0.14905595 0.94138629 0.60097784 0.        ]
 [0.         0.64063124 0.97396331 0.93891772 0.24079405 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [9]:
# Qn4: Using NumPy, create an array of integers from 10 to 60 with a step of 5.

# code->
arr = np.arange(10, 61, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [10]:
# Qn5: Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

# code->
str = np.array(['python', 'numpy', 'pandas'])
str

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [11]:
str.dtype


dtype('<U6')

In [12]:
str.ndim

1

In [13]:
# Applying various string manipulation functions from np.char module

In [14]:
np.char.upper(str)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [15]:
np.char.lower(str)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [16]:
np.char.capitalize(str) 

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [17]:
np.char.swapcase(str) #convert lowercase into uppercase and vice versa

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [18]:
np.char.title(str) # Capitalizing the first character of each word in the string

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [19]:
# Qn6: Generate a NumPy array of words. Insert a space between each character of every word in the array

# code->
arr = np.array(['hello', 'world'])
spaced_arr = np.char.join(' ', arr)
print("Original Array:\n", arr)
print("Array with spaces between characters:\n", spaced_arr)

Original Array:
 ['hello' 'world']
Array with spaces between characters:
 ['h e l l o' 'w o r l d']


In [20]:
# Qn7:. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

# code->
arr1 = np.random.randint(1,10,(3,3))
arr1

array([[9, 5, 4],
       [9, 2, 9],
       [6, 2, 2]])

In [21]:
arr2 = np.random.randint(1,10,(3,3))
arr2

array([[2, 5, 7],
       [6, 5, 6],
       [6, 2, 3]])

In [22]:
# Addition
arr1+arr2

array([[11, 10, 11],
       [15,  7, 15],
       [12,  4,  5]])

In [23]:
arr1-arr2

array([[ 7,  0, -3],
       [ 3, -3,  3],
       [ 0,  0, -1]])

In [24]:
arr1*arr2

array([[18, 25, 28],
       [54, 10, 54],
       [36,  4,  6]])

In [25]:
arr1/arr2

array([[4.5       , 1.        , 0.57142857],
       [1.5       , 0.4       , 1.5       ],
       [1.        , 1.        , 0.66666667]])

In [26]:
# Qn8:Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

# code->
identity_matrix = np.identity(5)
diagonal_elements = np.diag(identity_matrix)
print("5x5 Identity Matrix:\n", identity_matrix)
print()
print("Diagonal Elements:\n", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [27]:
# Qn9: Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

# code->
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

arr = np.random.randint(0, 1001, 100)
primes = arr[np.vectorize(is_prime)(arr)]
print("Random Array:\n", arr)
print()
print("Prime Numbers in Array:\n", primes)

Random Array:
 [300 199  92 386 417 703 599 623  22  55 415 309 496 846 736 257 824 837
 180 504 610 298  65 802 234 799 544 943 301 108 897 954 475 548 536 280
 566  77 916 700 974 919  85  24 923 861 471 543  31  75 827 890 417 901
 887  32 831 506 837 855 604 605 872 591 707 772 530  26 868 703  84  46
 705 289 279 471 245  38 972 681 143  76 285 432 128 956 635 649  27 509
 879 904 687  89 509 487 164 233 957 987]

Prime Numbers in Array:
 [199 599 257 919  31 827 887 509  89 509 487 233]


In [28]:
# Qn10: Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

# Ans:
daily_temperatures = np.random.randint(15, 36, 30)
daily_temperatures

array([28, 29, 18, 26, 18, 29, 25, 32, 22, 31, 18, 24, 27, 28, 19, 19, 16,
       17, 22, 24, 24, 31, 31, 15, 17, 27, 18, 25, 31, 31])

In [29]:
week1=daily_temperatures[0:7]
week2=daily_temperatures[7:14]
week3=daily_temperatures[14:21]
week4=daily_temperatures[21:28]

In [30]:
avg_week1=np.mean(week1)
avg_week2=np.mean(week2)
avg_week3=np.mean(week3)
avg_week4=np.mean(week4)

In [31]:
print("Average temperature of week1: ",avg_week1)
print("Average temperature of week2: ",avg_week2)
print("Average temperature of week3: ",avg_week3)
print("Average temperature of week4: ",avg_week4)


Average temperature of week1:  24.714285714285715
Average temperature of week2:  26.0
Average temperature of week3:  20.142857142857142
Average temperature of week4:  23.428571428571427
