In [1]:
import numpy as np

In [2]:
# Qn1: Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
# enhance Python's capabilities for numerical operations?

# Ans: 
# Purpose and Advantages:
# i.NumPy provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical 
#   functions to operate on these arrays. It is much faster than traditional Python lists because it uses C and Fortran code internally.
# ii.It simplifies the implementation of algorithms and the manipulation of large datasets. 
#    Operations on arrays are executed with fewer lines of code. 
#iii. Allows arithmetic operations on arrays of different shapes, simplifying code and improving performance.
#iv.It provides efficient storage of data by utilizing contiguous memory blocks, leading to faster access and processing.

In [3]:
# Qn2:Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
#     other?

# Ans:
# np.mean(): Computes the arithmetic mean along the specified axis, ignoring weights.
# np.average(): Computes the weighted average along the specified axis, where weights can be provided.
    
# Use Case:
# Use np.mean() when you want a simple average of the data.
# Use np.average() when you need to account for weights in your data (e.g., averaging grades with different credit hours).


In [4]:
# Qn3:Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
#     arrays.

In [5]:
# Ans: 
# 1D Array: Use slicing to reverse a 1D array.
# code->
arr = np.array([1, 2, 3, 4])
reversed_arr = arr[::-1]
print(reversed_arr)

[4 3 2 1]


In [6]:
# 2D Array: Use np.flip() or slicing to reverse along different axes.
# code->
arr = np.array([[1, 2, 3], [4, 5, 6]])
reversed_arr_0 = np.flip(arr, axis=0)  # Reverse rows
reversed_arr_1 = np.flip(arr, axis=1)  # Reverse columns
print(reversed_arr_0)
print(reversed_arr_1)

[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


In [7]:
# Qn4:How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

# Ans:
# Determine data type:
arr = np.array([1, 2, 3])
dtype = arr.dtype
print(dtype)

# Importance:
# Memory Management: NumPy allows for the specification of data types (e.g., int32, float64), which enables fine control over memory usage.
# Performance: Operations on arrays with smaller data types (e.g., int8 instead of int64) are faster and consume less memory, improving 
# performance especially in large datasets.

int64


In [8]:
# Qn5:Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

# Ans:
# Definition: An ndarray is a n-dimensional array in NumPy, representing a grid of values of the same data type.

# Key Features:
# Homogeneous: All elements are of the same type.
# Fixed size: Once created, the size cannot be changed.
# Vectorized operations: Supports element-wise operations

# Difference from Python Lists:
# Python lists can store elements of different types, while ndarrays are homogeneous.
# ndarrays are more memory-efficient and support more advanced mathematical operations.

In [9]:
# Qn6:Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

# Ans:
# Performance Benefits:
# Speed: NumPy arrays are faster due to their homogeneous nature and the fact that they are implemented in C.
# Memory Efficiency: They are stored in contiguous blocks of memory, leading to reduced overhead.
# Vectorization: Operations are applied element-wise, avoiding the need for explicit loops in Python.

In [10]:
# Qn7: Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

# Ans: Answers are below:

In [11]:
# vstack(): Stacks arrays vertically (row-wise).
# code->
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked = np.vstack((arr1, arr2))
# Output: [[1, 2, 3], [4, 5, 6]]
print(stacked)

[[1 2 3]
 [4 5 6]]


In [12]:
# hstack(): Stacks arrays horizontally (column-wise).
# code->
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked = np.hstack((arr1, arr2))
print(stacked)
# Output: [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [13]:
# Qn8: Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

# Ans:Answers are below:

In [14]:
# fliplr(): Flips the array in the left-right direction (horizontal flip). Applicable only to 2D arrays.
# code->
arr = np.array([[1, 2], [3, 4]])
flipped = np.fliplr(arr)
print(flipped)
# Output: [[2, 1], [4, 3]]

[[2 1]
 [4 3]]


In [15]:
# flipud(): Flips the array in the up-down direction (vertical flip). Applicable to both 1D and 2D arrays.
# code->
arr = np.array([[1, 2], [3, 4]])
flipped = np.flipud(arr)
print(flipped)
# Output: [[3, 4], [1, 2]]

[[3 4]
 [1 2]]


In [16]:
# flipud(): Flips the array in the up-down direction (vertical flip). Applicable to both 1D and 2D arrays.
# code->
arr = np.array([[1, 2], [3, 4]])
flipped = np.flipud(arr)
print(flipped)
# Output: [[3, 4], [1, 2]]

[[3 4]
 [1 2]]


In [17]:
# Qn9:. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

# Ans:
# Functionality: Splits an array into multiple sub-arrays. Handles uneven splits by distributing extra elements among the sub-arrays, 
#                ensuring that the first sub-arrays are larger.
# code->
arr = np.array([1, 2, 3, 4, 5])
split_arr = np.array_split(arr, 3)
print(split_arr)
# Output: [array([1, 2]), array([3, 4]), array([5])]

[array([1, 2]), array([3, 4]), array([5])]


In [18]:
# Qn10: Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

# Ans:
# Vectorization: Refers to performing operations on entire arrays rather than individual elements, 
#                enabling faster computations by utilizing optimized C libraries underneath.
# Broadcasting: Allows operations on arrays of different shapes by expanding the smaller array along the dimension to match the larger one.
# Efficiency: Both concepts eliminate the need for explicit loops, leading to more concise code and significant performance gains